devices_with_monitoring:
  - device_ip: 192.168.0.1
    device_name: switch_one
    protocol: NETCONF
    configs:
      - config:
          - interval: 1000
            counters:
              - name: myOwnIdentifier # name/id
                path: "elem: <name: 'interfaces' key: <key: 'namespace' value: 'urn:ietf:params:xml:ns:yang:ietf-interfaces'>> elem: <name: 'interface' key: <key:'name' value: 'sw0p1'>> elem: <name: 'ethernet' <key: 'namespace' value: 'urn:ieee:std:802.3:yang:ieee802-ethernet-interface'>> elem: <name: 'statistics'> elem: <name: 'frame'> elem: <name: 'in-total-frames'>"
              - name: total-frames
                path: "elem: <name: 'lldp' key: <key: 'namespace' value: 'urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp'>> elem: <name: 'port' key: <key:'name' value: 'sw0p3'>> elem: <name: 'tx-statistics'> elem: <name: 'total-frames'>"
      - config:
          - interval: 1000
            counters:
              - name: Ethernet_in-total-frames # name/id
                path: "elem: <name: 'interfaces' key: <key: 'namespace' value: 'urn:ietf:params:xml:ns:yang:ietf-interfaces'>> elem: <name: 'interface' key: <key:'name' value: 'sw0p1'>> elem: <name: 'ethernet' <key: 'namespace' value: 'urn:ieee:std:802.3:yang:ieee802-ethernet-interface'>> elem: <name: 'statistics'> elem: <name: 'frame'> elem: <name: 'in-total-frames'>"
          - interval: 2000
            counters:
              - name: test
                path: "elem: <name: 'lldp' key: <key: 'namespace' value: 'urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp'>> elem: <name: 'port' key: <key:'name' value: 'sw0p2'>> elem: <name: 'management-address-tx-port'> elem: <name: 'address-subtype'>"
      - config:
          - interval: 1000
            counters:
              - name: address-subtype # name/id
                path: "elem: <name: 'lldp' key: <key: 'namespace' value: 'urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp'>> elem: <name: 'port' key: <key:'name' value: 'sw0p2'>> elem: <name: 'management-address-tx-port'> elem: <name: 'address-subtype'>"
  - device_ip: 192.168.0.2
    device_name: switch_two
    protocol: NETCONF
    configs:
      - config:
          - interval: 1000
            counters:
              - name: total-frames # name/id
                path: "elem: <name: 'lldp' key: <key: 'namespace' value: 'urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp'>> elem: <name: 'port' key: <key:'name' value: 'sw0p3'>> elem: <name: 'tx-statistics'> elem: <name: 'total-frames'>"
      - config:
          - interval: 1000
            counters:
              - name: third # name/id
                path: ""
