devices_with_monitoring:
  - device_name: switch_one
    device_ip: 192.168.1.34
    protocol: NETCONF
    device_counters:
      - name: first
        interval: 5
        path: path1
      - name: second
        interval: 2
        path: path2
  - device_name: switch_two
    device_ip: 192.168.1.82
    protocol: NETCONF
    device_counters:
      - name: third
        interval: 2.5
        path: path3
      - name: fourth
        interval: 5
        path: path4
      - name: fifth
        interval: 10
        path: path5