devices_with_monitoring:
  - device_ip: 192.168.0.1
    device_name: switch_one
    protocol: NETCONF
    configs:
      - device_counters: # Could be renamed as config, to make it more clear what it is
          - name: Ethernet_in-total-frames # name/id
            interval: 10000 # ms
            path: "elem: <name: 'interfaces' key: <key: 'namespace' value: 'urn:ietf:params:xml:ns:yang:ietf-interfaces'>> elem: <name: 'interface' key: <key:'name' value: 'sw0p1'>> elem: <name: 'ethernet' <key: 'namespace' value: 'urn:ieee:std:802.3:yang:ieee802-ethernet-interface'>> elem: <name: 'statistics'> elem: <name: 'frame'> elem: <name: 'in-total-frames'>"
      - device_counters:
          - name: Ethernet_in-total-frames # name/id
            interval: 1000 # ms
            path: "elem: <name: 'interfaces' key: <key: 'namespace' value: 'urn:ietf:params:xml:ns:yang:ietf-interfaces'>> elem: <name: 'interface' key: <key:'name' value: 'sw0p1'>> elem: <name: 'ethernet' <key: 'namespace' value: 'urn:ieee:std:802.3:yang:ieee802-ethernet-interface'>> elem: <name: 'statistics'> elem: <name: 'frame'> elem: <name: 'in-total-frames'>"
  - device_ip: 192.168.0.2
    device_name: switch_two
    protocol: NETCONF
    configs:
      - device_counters:
          - name: total-frames # name/id
            interval: 15000 # ms
            path: "elem: <name: 'lldp' key: <key: 'namespace' value: 'urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp'>> elem: <name: 'port' key: <key:'name' value: 'sw0p3'>> elem: <name: 'tx-statistics'> elem: <name: 'total-frames'>"
      - device_counters:
          - name: third # name/id
            interval: 1.5
            path: "path3"
          - name: fourth # name/id
            interval: 2
            path: "path4"
          - name: fifth # name/id
            interval: 3
            path: "path5"